## 导入 Pandas

### 准备好使用 Pandas 吧！

难度： *简单* 

**1.** 以 `pd` 别名导入 pandas 库

In [379]:
import pandas as pd

**2.** 打印出导入 pandas 库的版本信息

In [380]:
print(pd.__version__)

3.0.1

**3.** 打印 pandas 依赖包及其 *版本* 信息

In [381]:
print(pd.__version__)
print(pd.show_versions())

3.0.1

INSTALLED VERSIONS
------------------
commit                : e04b26f375035e5106cb913e47b6db612f4ebb11
python                : 3.12.4
python-bits           : 64
OS                    : Windows
OS-release            : 11
Version               : 10.0.26300
machine               : AMD64
processor             : Intel64 Family 6 Model 170 Stepping 4, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : Chinese (Simplified)_China.936

pandas                : 3.0.1
numpy                 : 2.4.4
dateutil              : 2.9.0.post0
pip                   : 26.1.1
Cython                : None
sphinx                : None
IPython               : 9.12.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.14.3
bottleneck            : None
fastparquet           : None
fsspec                : 2026.3.0
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : 3.1.6
lxml.etree            : None
matplotlib            : 3.10.8
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.5
psycopg2              : None
pymysql               : None
pyarrow               : None
pyiceberg             : None
pyreadstat            : None
pytest                : None
python-calamine       : None
pytz                  : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.17.1
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
qtpy                  : None
pyqt5                 : None
None

## DataFrame：基础知识

### 使用 DataFrame 进行选择、排序、添加以及聚合数据。

难度： *简单*

提示： 记得使用如下命令导入 numpy：
```python
import numpy as np
```

有如下字典 `data` 以及列表 `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
（这只是以动物和看兽医为主题编造的一些无意义的数据）

**4.** 使用数据 `data` 和行索引 `labels` 创建一个 DataFrame `df`

In [382]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**5.** 显示该 DataFrame 及其数据相关的基本信息（*提示：DataFrame 直接调用的方法*）

In [383]:
df.info()

<class 'pandas.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     str
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     str
dtypes: float64(1), int64(1), str(2)
memory usage: 400.0+ bytes

**6.** 返回 DataFrame `df` 的前三行数据

In [384]:
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

**7.** 从 DataFrame `df` 选择标签为 `animal` 和 `age` 的列

In [385]:
df[['animal', 'age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

**8.** 在 `[3, 4, 8]` 行中 *且* 列为 `['animal', 'age']` 的数据

In [386]:
df.iloc[[3, 4, 8]][['animal', 'age']]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

**9.** 选择 `visits` 大于 3 的行

In [387]:
df[df['visits'] > 3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

**10.** 选择 `age` 为缺失值的行，如 `NaN`

In [388]:
df[df['age'].isna()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

**11.** 选择 `animal` 是 cat *且* `age` 小于 3 的行

In [389]:
df[(df['animal'] == 'cat') & (df['age'] < 3)]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

**12.** 选择 `age` 在 2 到 4 之间的数据（包含边界值）

In [390]:
df[df['age'].between(2, 4)]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

**13.** 将 'f' 行的 `age` 改为 1.5

In [391]:
df.loc['f', 'age'] = 1.5

**14.** 计算 `visits` 列的数据总和

In [392]:
df['visits'].sum()

np.int64(19)

**15.** 计算每种 `animal` `age` 的平均值

In [393]:
df.groupby('animal')['age'].mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

**16.** 追加一行 k，列的数据自定义，然后再删除新追加的 k 行

In [394]:
df.loc['k'] = ['rabbit', 3.0, 2, 'no']
df = df.drop('k')

**17.** 计算每种 `animal` 的总数

In [395]:
df['animal'].value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

**18.** 先根据 `age` 降序排列，再根据 `visits` 升序排列（结果 `i` 列在前面，`d` 列在最后面）

In [396]:
df.sort_values(by=['age', 'visits'], ascending=[False, True])

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

**19.** 将 `priority` 列的 `yes` 和 `no` 用 `True` 和 `False` 替换

In [397]:
df['priority'] = df['priority'].map({'yes': True, 'no': False})

**20.** 将 `animal` 列的 `snake` 用 `python` 替换

In [398]:
df['animal'] = df['animal'].replace('snake', 'python')

**21.** 对于每种 `animal` 和 `visit`，求出平均年龄。换句话说，每一行都是动物，每一列都是访问次数，其值是平均年龄（提示：使用数据透视表）

In [399]:
df.pivot_table(index='animal', columns='visits', values='age', aggfunc='mean')

visits    1    2     3
animal
cat     2.5  NaN  2.25
dog     3.0  6.0   NaN
python  4.5  0.5   NaN

## DataFrame：更上一层楼

### 有点困难了！你可能需要结合两种或以上的方法才能得到正确的解答。

难度: *中等*

上一章节是一些简单但是相当实用的 DataFrame 操作。本章节将介绍如何切割数据，但是并没有开箱即用的方法。

**22.** 假设现在有一个一列整数 `A` 的 DataFrame `df`，比如：
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

你怎么样把重复的数据去除？

剩下的数据应该像下面一样：

```python
1, 2, 3, 4, 5, 6, 7
```

In [400]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
df['A'].unique()

array([1, 2, 3, 4, 5, 6, 7])

**23.** 给定一组随机数据
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # a 5x3 frame of float values
```

如何使每个元素减去所在行的平均值？

In [401]:
df = pd.DataFrame(np.random.random(size=(5, 3)))
df.sub(df.mean(axis=1), axis=0)

          0         1         2
0  0.120904 -0.239957  0.119053
1  0.221234 -0.320366  0.099131
2 -0.031728 -0.021414  0.053142
3  0.179261 -0.210021  0.030760
4  0.080892  0.145630 -0.226522

**24.** 假设你有 10 列实数：

```python
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
```
返回数字总和最小那列的标签

In [402]:
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
df.sum().idxmin()

'f'

**25.** 如何计算一个 DataFrame 有多少唯一的行（即忽略所有重复的行）？

```python
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))
```

In [403]:
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))
len(df.drop_duplicates())

6

后面三题会更加难！做好准备了吗？


**26.** 
给定一个十列的 DataFrame `df`，每行恰好有 5 个 `NaN` 值，从中找出第三个是 `NaN` 值的列标签。
返回结果如： `e, c, d, h, d`

In [404]:
nan = np.nan

data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)

df.apply(lambda x: x.isna().cumsum().eq(3).idxmax(), axis=1)

0    e
1    c
2    d
3    h
4    d
dtype: str

**27.** DataFrame 如下 

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
对于每组（即a，b，c 三组），找到三个数相加的最大和
```
grps
a    409
b    156
c    345
```

In [405]:
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})

result = df.groupby('grps')['vals'].apply(lambda x: x.nlargest(3).sum())
print(result)

grps
a    409
b    156
c    345
Name: vals, dtype: int64

**28.** 
`DataFrame` 数据如下，`A` 和 `B` 都是 0-100 之间（包括边界值）的数值，对 `A` 进行分段分组（i.e. `(0, 10]`, `(10, 20]`, ...），求每组内 `B` 的和。输出应该和下述一致：

```
A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
```

In [406]:
df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])

df.groupby(pd.cut(df['A'], bins=range(0, 101, 10))).sum()['B']

A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
Name: B, dtype: int32

## DataFrame：向你发出挑战 

### 这里可能需要一点突破常规的思维……

但所有这些都可以使用通常的 pandas/NumPy 方法来解决（因此避免使用的`for` 循环来解决）。

难度: *困难*

**29.** 假设存在一列整数 `X`
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```
对于每一个元素，计算其与上一个 `0` 或者列的开头之间的距离（哪一个更小就取哪个，若自身为 0 则值为 0），结果应该如下：

```
[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
```

生成新列 `Y`

In [407]:
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})

x = df['X']
zeros = x == 0
cumsum = zeros.cumsum()
df['Y'] = (x.groupby(cumsum).cumcount() + 1) * (~zeros)
df['Y']

0    1
1    2
2    0
3    2
4    3
5    4
6    5
7    0
8    2
9    3
Name: Y, dtype: int64

**30.** 
求出最大的三个值的索引位置，结果应该如下：
```
[(5, 7), (6, 4), (2, 5)]
```

In [408]:
df = pd.DataFrame(np.random.RandomState(30).randint(1, 101, size=(8, 8)))

df.stack().nlargest(3).index.tolist()

[(5, 2), (4, 6), (7, 5)]

**31.** 给定如下数据

```python
df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15), 
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})
```

创建一个新列 `patched_values`，当 `vals`为正数时，`patched_value` 的值为`vals` 本身；当 `vals` 为负时，`patched_value` 的值等于所在组的正数的平均值
```
    vals grps  patched_vals
0    -12    A          13.6
1     -7    B          28.0
2    -14    A          13.6
3      4    A           4.0
4     -7    A          13.6
5     28    B          28.0
6     -2    A          13.6
7     -1    A          13.6
8      8    A           8.0
9     -2    B          28.0
10    28    A          28.0
11    12    A          12.0
12    16    A          16.0
13   -24    A          13.6
14   -12    A          13.6
```

In [409]:
df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15), 
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})

df['patched_vals'] = df.apply(lambda x: x['vals'] if x['vals'] > 0 else df[(df['grps'] == x['grps']) & (df['vals'] > 0)]['vals'].mean(), axis=1)
df

    vals grps  patched_vals
0    -12    A          13.6
1     -7    B          28.0
2    -14    A          13.6
3      4    A           4.0
4     -7    A          13.6
5     28    B          28.0
6     -2    A          13.6
7     -1    A          13.6
8      8    A           8.0
9     -2    B          28.0
10    28    A          28.0
11    12    A          12.0
12    16    A          16.0
13   -24    A          13.6
14   -12    A          13.6

**32.** 对窗口大小为 3 的组实施滚动均值，忽略 NaN 值，给定数据如下

```python
>>> df = pd.DataFrame({'group': list('aabbabbbabab'),
                       'value': [1, 2, 3, np.nan, 2, 3, np.nan, 1, 7, 3, np.nan, 8]})
>>> df
   group  value
0      a    1.0
1      a    2.0
2      b    3.0
3      b    NaN
4      a    2.0
5      b    3.0
6      b    NaN
7      b    1.0
8      a    7.0
9      b    3.0
10     a    NaN
11     b    8.0
```
目标是计算该 Series

```
0     1.000000
1     1.500000
2     3.000000
3     3.000000
4     1.666667
5     3.000000
6     3.000000
7     2.000000
8     3.666667
9     2.000000
10    4.500000
11    4.000000
```

例如，第一个大小为 3 的窗口 `b` 组的值为 3.0、NaN 和 3.0。在第三行索引的新列中的值应该是 3.0，而不是 NaN（用两个非 NaN 值来计算平均值（3+3）/2）。

In [410]:
df = pd.DataFrame({'group': list('aabbabbbabab'),
                   'value': [1, 2, 3, np.nan, 2, 3, np.nan, 1, 7, 3, np.nan, 8]})

df.groupby('group')['value'].rolling(3, min_periods=1).mean().reset_index(0, drop=True)

0     1.000000
1     1.500000
4     1.666667
8     3.666667
10    4.500000
2     3.000000
3     3.000000
5     3.000000
6     3.000000
7     2.000000
9     2.000000
11    4.000000
Name: value, dtype: float64

## Series 和 DatetimeIndex

### 使用时间数据创建和操作 Series 对象。

难度: *简单/中等*

pandas 在处理日期与时间方面非常出色，这部分将探索 pandas 这方面的功能。

**33.** 创建一个 Series `s`，其索引为 2015 年的工作日，值可以随机取

In [411]:
s = pd.Series(np.random.randn(len(pd.bdate_range('2015-01-01', '2015-12-31'))),
              index=pd.bdate_range('2015-01-01', '2015-12-31'))
s

2015-01-01    0.514490
2015-01-02   -0.889179
2015-01-05   -1.081107
2015-01-06   -0.120963
2015-01-07    1.038375
                ...
2015-12-25    0.969639
2015-12-28    0.571914
2015-12-29    0.107434
2015-12-30    1.080098
2015-12-31   -0.555977
Freq: B, Length: 261, dtype: float64

**34.** 计算日期是周三（Wednesday）的值的总和

In [412]:
s[s.index.dayofweek == 2].sum()

np.float64(-0.9209906300534796)

**35.** 计算每个月的平均值

In [413]:

s.resample('ME').mean()

print(s.resample('ME').mean())

2015-01-31   -0.174643
2015-02-28    0.056239
2015-03-31    0.109751
2015-04-30    0.095124
2015-05-31   -0.422497
2015-06-30    0.179875
2015-07-31   -0.054248
2015-08-31    0.201317
2015-09-30    0.238079
2015-10-31   -0.032091
2015-11-30   -0.092782
2015-12-31    0.070312
Freq: ME, dtype: float64

**36.** 寻找每个季度内最大值所对应的日期

In [414]:
result = s.groupby(pd.Grouper(freq='QE')).idxmax()
print(result)

2015-03-31   2015-02-10
2015-06-30   2015-06-22
2015-09-30   2015-08-25
2015-12-31   2015-11-19
Freq: QE-DEC, dtype: datetime64[us]

**37.** 创建一个 DataTimeIndex，包含 2015 年至 2016 年每个月的第三个星期四

In [415]:
pd.date_range('2015-01-01', '2016-12-31', freq='WOM-3THU')
print(pd.date_range('2015-01-01', '2016-12-31', freq='WOM-3THU'))

DatetimeIndex(['2015-01-15', '2015-02-19', '2015-03-19', '2015-04-16',
               '2015-05-21', '2015-06-18', '2015-07-16', '2015-08-20',
               '2015-09-17', '2015-10-15', '2015-11-19', '2015-12-17',
               '2016-01-21', '2016-02-18', '2016-03-17', '2016-04-21',
               '2016-05-19', '2016-06-16', '2016-07-21', '2016-08-18',
               '2016-09-15', '2016-10-20', '2016-11-17', '2016-12-15'],
              dtype='datetime64[us]', freq='WOM-3THU')